name: ChatApp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Release image
      - name: Build Release Docker image
        run: |
          docker build \
            --build-arg BUILD_TYPE=Release \
            --target release \
            -t chat-app:release .

      # 4. Build Debug image
      - name: Build Debug Docker image
        run: |
          docker build \
            --build-arg BUILD_TYPE=Debug \
            --target debug \
            -t chat-app:debug .

      # 5. Build Test image
      - name: Build Test Docker image
        run: |
          docker build \
            --target test \
            -t chat-app:test .

      # 6. Run Ceedling tests
      - name: Run unit tests
        run: docker run --rm chat-app:test
